[window]
dimensions = { columns = 88, lines = 25}
decorations_theme_variant = "Dark"
opacity = 0.95
blur = true

[font]
size = 18.0

[font.normal]
family = "Comic Code Ligatures"
style = "Regular"

[font.bold]
family = "Comic Code Ligatures"
style = "Bold"

[font.italic]
family = "Comic Code Ligatures"
style = "Italic"

[font.bold_italic]
family = "Comic Code Ligatures"
style = "Bold Italic"

[cursor]
style = { blinking = "Always" }
blink_timeout = 0

# Paper Like
#[colors.primary]
#background = '#F2EEDE'
#foreground = '#000000'
#
#[colors.normal]
#black = '#000000'
#red = '#CC3E28'
#green = '#216609'
#yellow = '#B58900'
#blue = '#1E6FCC'
#magenta = '#5C21A5'
#cyan = '#158C86'
#white = '#AAAAAA'
#
#[colors.bright]
#black = '#555555'
#red = '#CC3E28'
#green = '#216609'
#yellow = '#B58900'
#blue = '#1E6FCC'
#magenta = '#5C21A5'
#cyan = '#158C86'
#white = '#AAAAAA'


# Hyper
[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[colors.cursor]
text = "0xF81CE5"
cursor = "0xffffff"

[colors.normal]
black = "0x000000"
red = "0xfe0100"
green = "0x33ff00"
yellow = "0xfeff00"
blue = "0x0066ff"
magenta = "0xcc00ff"
cyan = "0x00ffff"
white = "0xd0d0d0"

[colors.bright]
black = "0x808080"
red = "0xfe0100"
green = "0x33ff00"
yellow = "0xfeff00"
blue = "0x0066ff"
magenta = "0xcc00ff"
cyan = "0x00ffff"
white = "0xFFFFFF"
